name: HalfYear
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "template"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest

with:
  token: ${{ secrets.METRICS_TOKEN }}
  filename: metrics.plugin.isocalendar.svg
  base: ""
  plugin_isocalendar: yes
