name: Remove Expired Workflow Runs
on:
  schedule: [{ cron: "30 1 * * *" }] # Schedule to run the workflow every day at 1:30 AM
  workflow_dispatch:

jobs:
  clean:
    name: Clean Expired Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action Code
        uses: actions/checkout@v2

      - name: Run Cleaner Script
        run: sh ./cleaner.sh long18 long18
        working-directory: .github/actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
