# Licensed under The Unlicense
# Feel free to reuse, edit and redistribute this workflow as you wish, no credits needed
# See https://github.com/lowlighter/metrics for documentation about how to use metrics action

name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Schedule to run every hour
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:

      - name: 🤡 Medias
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: medias.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_order: anilist
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 1
          plugin_anilist_limit_characters: 22
          plugin_anilist_user: william18
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 9

      - name: 🤡 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      - name: 🤡 Sponsors
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount

      - name: 🤡 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, dockerfile, javascript
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_notable: yes
