name: Stale issues, pr and runs

on:
  schedule: [{cron: "30 1 * * *"}] # Schedule to run the workflow every day at 1:30 AM
  workflow_dispatch:
    inputs:
      owner:
        description: 'Owner Name'
        required: true
        type: string
      repo:
        description: 'Repository Name'
        required: true
        type: string

jobs:
  stale:
    name: Flag stale issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          days-before-stale: -1
          stale-pr-message: This pull request seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          days-before-pr-stale: 90
          days-before-pr-close: 7
          stale-pr-label: ⏹️ stale
          remove-stale-when-updated: yes
          exempt-issue-labels: 📦 dependencies
  lock:
    name: Lock inactive closed issues and pull requests
    needs:
      - stale
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.METRICS_TOKEN }}
          issue-inactive-days: 180
          issue-lock-reason: ""
          add-issue-labels: ☑️ archived
          pr-inactive-days: 180
          pr-lock-reason: ""
          add-pr-labels: ☑️ archived
  workflows:
    name: Remove expired workflow runs
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run script
        run: git update-index --chmod=+x ./delete_workflows.sh  
        working-directory: .github/actions/ghcr-clean
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          OWNER: ${{ inputs.owner }}
          REPO: ${{ inputs.repo }}
